config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index'
  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :category
  validates :title, :content, :category_id, presence: true
  has_many :line_items, inverse_of: :order
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy]

  def index
    if params[:category].blank?
    @posts = Post.all.order("created_at DESC")
    else
    @category_id = Category.find_by(name: params[:category]).id
    @posts = Post.where(category_id: @category_id).order("created_at DESC")
    end
  end

  def show
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
     if @post.save
          redirect_to @post, notice: "The post was created!"
     else
          render 'new'
     end
  end

  def edit
  end

  def update
    if @post.update(post_params)
          redirect_to @post, notice: "Update successful"
     else
          render 'edit'
     end
  end

  def destroy
    @post.destroy
    redirect_to root_path, notice: "Post destroyed"
  end

private

  def post_params
    params.require(:post).permit(:title, :content, :category_id, :image)
  end

  def find_post
    @post = Post.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>Marmelade</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class=”navbar navbar-default navbar-fixed-top”>
      <div class=”container-fluid”>
        <%= render 'shared/nav' %>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="container">
  <%= form_for @post, html: { multipart: true } do |f| %>

    <%= render 'shared/error_messages' %>

    <%= f.collection_select(:category_id, Category.all, :id, :name, {prompt: "Choose a category" }) %><br>
    <%= f.label :title %><br>
    <%= f.text_field :title, placeholder: "Type the post title here" %><br>
    <%= f.label :content %><br>
    <%= f.text_area :content, size: "60x12", placeholder: "Type the post tect here" %><br>

    <%= f.label :image %><br>
    <%= f.file_field :image %><br>

    <%= f.submit %>

  <% end %>
</div>

app/views/posts/edit.html.erb
<div class="container">
  <h1>Edit Post</h1>
  <%= render 'form' %>
  <%= link_to "Back", root_path %>
</div>

app/views/posts/index.html.erb
<div class="container">
  <% @posts.each do |post| %>
       <h1><%= link_to post.title, post %></h1>
       <p><%= post.content %></p>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="container">
  <h1>New Post</h1>
  <%= render 'form' %>
  <%= link_to "Back", root_path %>
</div>

app/views/posts/show.html.erb
<div class="container">

    <%= image_tag @post.image_url.to_s, alt: "Image", class: "post_bumper" %>


  <h1><%= @post.title %></h1>
  <p><%= @post.content %></p>
  <%= link_to "Edit", edit_post_path(@post) %>
  <%= link_to "Delete", @post, method: :delete, data: { confirm: "Are you sure?" }%>
</div>

app/views/shared/_error_messages.html.erb
<% if @post.errors.any? %>
  <div>
    <span class="label label-warning">Warning</span>
    <p><%= pluralize(@post.errors.count, "error") %> prevented this post from saving.</p>
    <ul>
      <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Marmelade</a>
    </div>

    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <% Category.all.each do |category| %>
          <li>
          <%= link_to category.name, posts_path(category: category.name) %>
          </li>
        <% end %>
      </ul>
<!--       <ul class="nav navbar-nav navbar-right">
        <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
        <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
      </ul> -->
    </div>

  </div>
</nav>